import { COLORS, TYPOGRAPHY, RADIUS, SHADOWS, SPACING, TRANSITIONS } from "@/constants/tokens";

export const antdTheme = {
  token: {
    colorPrimary: COLORS.primary,
    colorInfo: COLORS.info,
    colorSuccess: COLORS.success,
    colorWarning: COLORS.warning,
    colorError: COLORS.error,
    colorTextBase: COLORS.text,
    colorTextSecondary: COLORS.textSecondary,
    colorBgBase: COLORS.background,
    colorBgContainer: COLORS.surface,
    colorBorder: COLORS.border,
    colorBorderSecondary: COLORS.border,
    borderRadius: RADIUS.sm,
    borderRadiusLG: RADIUS.lg,
    borderRadiusSM: RADIUS.sm,
    fontFamily: TYPOGRAPHY.fontFamily,
    fontSize: 16,
    fontSizeHeading1: 40,
    fontSizeHeading2: 32,
    fontSizeHeading3: 24,
    fontSizeHeading4: 20,
    fontSizeHeading5: 18,
    fontWeightStrong: TYPOGRAPHY.fontWeight.semibold,
    lineHeight: TYPOGRAPHY.lineHeight.normal,
    controlHeight: 44,
    controlHeightLG: 52,
    controlHeightSM: 36,
    paddingContentHorizontal: SPACING.md,
    paddingContentVertical: SPACING.sm,
    boxShadow: SHADOWS.md,
    boxShadowSecondary: SHADOWS.sm,
    motionDurationMid: TRANSITIONS.base,
  },
  components: {
    Button: {
      primaryShadow: "none",
      defaultShadow: "none",
      dangerShadow: "none",
      fontWeight: TYPOGRAPHY.fontWeight.semibold,
      controlHeight: 44,
      controlHeightLG: 52,
      controlHeightSM: 36,
      borderRadius: RADIUS.sm,
      borderRadiusLG: RADIUS.md,
      paddingInline: SPACING.lg,
      paddingInlineLG: SPACING.xl,
    },
    Input: {
      controlHeight: 44,
      controlHeightLG: 52,
      controlHeightSM: 36,
      borderRadius: RADIUS.sm,
      paddingInline: SPACING.md,
      colorBorder: COLORS.border,
      activeBorderColor: COLORS.primary,
      hoverBorderColor: COLORS.secondary,
    },
    Select: {
      controlHeight: 44,
      borderRadius: RADIUS.sm,
    },
    Card: {
      borderRadiusLG: RADIUS.lg,
      boxShadow: SHADOWS.card,
      paddingLG: SPACING.lg,
    },
    Form: {
      labelColor: COLORS.text,
      labelFontSize: 14,
      itemMarginBottom: SPACING.lg,
    },
    Menu: {
      itemBorderRadius: RADIUS.sm,
      itemHeight: 44,
    },
  },
};
